[package]
name = "dns-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
dns = { path = "../app" }

[build-dependencies]
gwasm-builder.workspace = true
sails-idl-gen.workspace = true
dns = { path = "../app" }
